### ISSUE TITLE
Refreshing the page with multiple documents always loads comments for the rightmost document

### ISSUE THREAD

**Issue by cameron-toy** [jupytercalpoly/jupyterlab-comments#103]
The behavior only seems to occur when switching documents rapidly. The header on the comment panel also shows the title of the correct document but comments are being displayed for the incorrect one.

![reload_bug](https://user-images.githubusercontent.com/38936057/128440099-21623ece-663e-48d4-afaa-416198449332.gif)

**Comment by srirag-vuppala** [comment]
Fixed in recent PRs
