### ISSUE TITLE
the placeholder textarea looks smallish on first comment

### ISSUE THREAD

**Issue by goanpeca** [jupytercalpoly/jupyterlab-comments#141]
Awesome project!

The first time I was testing this, the placeholder textarea looks smallish, it restores after typing

<img width="254" alt="Screen Shot 2021-08-30 at 11 07 42 AM" src="https://user-images.githubusercontent.com/3627835/131370483-700a1ea3-5a94-46ff-889f-64e123d6371e.png">

**Comment by cameron-toy** [comment]
Thank you for the issue @goanpeca ! Would you mind adding what browser and OS you're using?

**Comment by goanpeca** [comment]
Google Chrome
Version 92.0.4515.159 (Official Build) (x86_64)
On a Mac

**Comment by cameron-toy** [comment]
Issue was due to how default contenteditable height is handled across browsers--adding a `min-height` should fix it #143
