### ISSUE TITLE
Create comments token/API

### ISSUE THREAD

**Issue by cameron-toy** [jupytercalpoly/jupyterlab-comments#63]
The comment system currently only works for Notebooks. However, the goal of this extension is to support commenting for  a variety of documents.

To do this, a token (`ICommentRegistry` or something) should be added. This token should provide access to the comments panel, allow registering comment targets/types, and have an API for adding/deleting/editing/replying to comments. Comments should be saved server-side in files, with one file for each commented document. A good starting point would be to provide the panel as a token and go from there.

As the comment API is developed, the Notebook implementation should be incrementally changed to take advantage of it.

Related:
- [x] #73 
- [x] #74 
- [x] #75

**Comment by aiqc** [comment]
Does a variety of documents mean .md and .txt files in jupyterlab?

**Comment by cameron-toy** [comment]
@aiqc Yes! All single document, "text-editor-like" file formats (.md, .txt, .py, .r, etc) use the same underlying `CodeEditor` so a comment that targets this underlying editor can be created and used for any of those files.

**Comment by aiqc** [comment]
the question that comes to mind is "how will you show what line of code/ text the comment refers to" when there is no concept of cell. ideally, notebook comments would be attributable to a specific line or highlighted section of code/ md?

**Comment by cameron-toy** [comment]
Addressed by PR #83
