### ISSUE TITLE
open comment sidebar after adding comment

### ISSUE THREAD

**Issue by aiqc** [jupytercalpoly/jupyterlab-comments#87]
my first question after adding a comment is "where did it go?" 

I took a guess and clicked on the dot dot dot sidebar icon, but it would be nice if this opened on its own

maybe it's better to just create comments using the sidebar to begin with?

**Comment by srirag-vuppala** [comment]
Hello @aiqc , Thanks for the issue!

I think that would be a good quality of life feature, I'll add it into our roadmap.

**Comment by cameron-toy** [comment]
Addressed by PR #93
