### ISSUE TITLE
chat bubble icon in sidebar?

### ISSUE THREAD

**Issue by aiqc** [jupytercalpoly/jupyterlab-comments#88]
![image](https://user-images.githubusercontent.com/74990642/127364469-bc155aa5-e2cd-4ff5-ba9d-60fdcf36bc09.png)

^ this to me says something like "logs"

![image](https://user-images.githubusercontent.com/74990642/127364506-5829303b-66e2-4199-9115-82ca5940b159.png)

^ versus something like this means comments

**Comment by srirag-vuppala** [comment]
Hello @aiqc, Thank you for the issue! 
We have plans of adding a logo that looks something like this 
![image](https://user-images.githubusercontent.com/59373265/127372052-838b3a96-5776-44a5-b1cd-8a7cba464733.png)

I'll add this issue in our todo section for our roadmap!

**Comment by cameron-toy** [comment]
Addressed by PR #95

**Comment by cameron-toy** [comment]
Addressed by PR #95
