### ISSUE TITLE
textbox size when creating a comment

### ISSUE THREAD

**Issue by aiqc** [jupytercalpoly/jupyterlab-comments#90]
![image](https://user-images.githubusercontent.com/74990642/127365966-1cff2343-4d70-454f-b122-014c9f2d1550.png)

^ when adding a comment people need to be both constructive + nice. that's a lot to fit in the small text area of the popup. 

Also, maybe it's better to just create the comment from the sidebar when right-clicking `add comment`

**Comment by srirag-vuppala** [comment]
Hi @aiqc , Thanks for the issue!

Thanks for bringing this up, our team also agrees that we need to find an alternative for the `InputDialog`. We'll try and make a custom text input as that would also fix the #92 issue. 

I think the placement for having it situated in the comment panel makes sense too!

**Comment by cameron-toy** [comment]
Closed by PR #96
