### ISSUE TITLE
clearing outputs deletes the comment indicator/ orangeness

### ISSUE THREAD

**Issue by aiqc** [jupytercalpoly/jupyterlab-comments#91]
![image](https://user-images.githubusercontent.com/74990642/127366563-19f4d164-7cde-4195-8636-0b3dcc325f33.png)

it's a frequent use case to 'clear the output' of notebook cells. in doing so it got rid of the dot next to the cell number and changed from orange to blue 

and now when i run cells, the numbers are not reappearing. i'd say to just experiment with clearing the output on commented notebooks.

when i restart the kernel, the comment indicator next to the cell does not reappear.

might want to check the effect of expanding/ collapsing cells too

**Comment by aiqc** [comment]
i love that comments are persisted when exporting the file

![image](https://user-images.githubusercontent.com/74990642/127368180-0eaa5094-e72a-46a7-92aa-fe1cffccc893.png)

**Comment by srirag-vuppala** [comment]
Fixed in recent PRs
